name: Build & Deploy NextJS (Node 20 → SSH)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
  SSH_HOST:   ${{ secrets.SSH_HOST }}
  SSH_USER:   ${{ secrets.SSH_USER }}
  SSH_PORT:   ${{ secrets.SSH_PORT || 22 }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build

      # --- SSH setup (adds your private key to an agent) ---
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" -H "$SSH_HOST" >> ~/.ssh/known_hosts

      # (optional) ensure the remote directory exists
      - name: Create remote directory if needed
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "mkdir -p '$REMOTE_PATH'"

      # --- Deploy with rsync over SSH ---
      - name: Deploy via rsync
        run: |
          rsync -az --delete -e "ssh -p $SSH_PORT" "$BUILD_DIR/" "$SSH_USER@$SSH_HOST:$REMOTE_PATH/"
