name: Build & Deploy NextJS (Node 20 → SSH)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
  SSH_HOST:   ${{ secrets.SSH_HOST }}
  SSH_USER:   ${{ secrets.SSH_USER }}
  SSH_PORT:   ${{ secrets.SSH_PORT || 22 }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: yarn install
      
      - name: Run script file to get build date
        run: node git-version.js
  
      - name: Build
        run: yarn build

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: Remove NextJS build folder
        run: |
          ssh -i private-key.pem \
              -o UserKnownHostsFile=./known_hosts \
              ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "rm -rf /home/ubuntu/test-github-action/.next && mkdir /home/ubuntu/test-github-action/.next"

      - name: Copy NextJS build folder
        run: |
          scp -i private-key.pem \
          -o StrictHostKeyChecking=yes \
          -o UserKnownHostsFile=./known_hosts \
          -P ${{ env.SSH_PORT }} \
          -r .next/* ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:/home/ubuntu/test-github-action/.next/

      - name: Install yarn dependencies in server and restart
        run: |
          ssh -i private-key.pem \
              -o UserKnownHostsFile=./known_hosts \
              ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "cd /home/ubuntu/test-github-action && source ~/.nvm/nvm.sh && nvm use 20 && git pull && yarn && sudo service test-github-action restart"

      - name: remove key and echo success
        run: rm private-key.pem && echo "Run Success"